import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function PageLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {/* <Header /> */}
            <div className="flex item-center justify-center w-full h-screen">
                {children}
            </div>
        </>
    )
}
